# Generated by Django 4.0.5 on 2022-06-17 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0002_nft'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='content',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='created_by',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='nft',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetManager.nft'),
        ),
        migrations.AddField(
            model_name='asset',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='unit_name',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
