# Generated by Django 4.0.5 on 2022-06-17 05:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0003_remove_asset_content_remove_asset_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_id', models.IntegerField(blank=True, null=True)),
                ('app_nft', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='assetManager.nft')),
            ],
        ),
    ]
