# Generated by Django 4.0.5 on 2022-06-17 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0004_application'),
    ]

    operations = [
        migrations.AddField(
            model_name='nft',
            name='is_bidder',
            field=models.BooleanField(default=False),
        ),
    ]
