# Generated by Django 4.0.5 on 2022-06-17 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assetManager', '0005_nft_is_bidder'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_bidded',
            field=models.BooleanField(default=False),
        ),
    ]
